version: "3.6"

networks:
networks:
  splunknet:
    driver: bridge
    attachable: true

services:
  cribl-leader1:
    networks:
      splunknet:
        aliases: 
          - cribl-leader1
    image: ${CRIBL_IMAGE:-cribl/cribl:latest}
    hostname: cribl-leader1
    container_name: cribl-leader1
    environment:
      - CRIBL_DIST_MODE=master
      - CRIBL_DIST_MASTER_URL=tcp://criblmaster@0.0.0.0:4200
      - CRIBL_VOLUME_DIR=/opt/cribl/config-volume
    ports:
      - 9000:9000
      - 4200

  cribl-worker1:
    networks:
      splunknet:
        aliases: 
          - cribl-worker1
    image: ${CRIBL_IMAGE:-cribl/cribl:latest}
    hostname: cribl-worker1
    container_name: cribl-worker1
    environment:
      - CRIBL_DIST_MODE=worker
      - CRIBL_DIST_MASTER_URL=tcp://criblmaster@cribl-leader1:4200
    ports:
      - 9001:9000
      - 5114:514

  cribl-worker2:
    networks:
      splunknet:
        aliases: 
          - cribl-worker2
    image: ${CRIBL_IMAGE:-cribl/cribl:latest}
    hostname: cribl-worker2
    container_name: cribl-worker2
    environment:
      - CRIBL_DIST_MODE=worker
      - CRIBL_DIST_MASTER_URL=tcp://criblmaster@cribl-leader1:4200
    ports:
      - 9002:9000
      - 5214:514